# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-06 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='ip\u5730\u5740')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8282\u70b9IP\u7ba1\u7406',
                'verbose_name_plural': '\u8282\u70b9IP\u7ba1\u7406',
            },
        ),
        migrations.AddField(
            model_name='node',
            name='max_num',
            field=models.IntegerField(default=10, help_text='\u5355\u4f4d: \u6b21/\u5929(\u540c\u9879\u76ee\u540cip)', verbose_name='\u6700\u5927\u4efb\u52a1\u9891\u5ea6'),
        ),
        migrations.AddField(
            model_name='node',
            name='ips',
            field=models.ManyToManyField(to='distribute.NodeIp', verbose_name='\u5386\u53f2IP'),
        ),
        migrations.AddField(
            model_name='nodetask',
            name='nodeip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distribute.NodeIp', verbose_name='\u6267\u884cIP'),
        ),
    ]
