# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u57df\u540d\u767d\u540d\u5355',
                'verbose_name_plural': '\u57df\u540d\u767d\u540d\u5355\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='CycleObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'\xe4\xb8\x8d\xe8\xa6\x81\xe8\xbe\x93\xe5\x85\xa5\xe4\xb8\xad\xe6\x96\x87\xe5\x92\x8c\xe7\x89\xb9\xe6\xae\x8a\xe7\xac\xa6\xe5\x8f\xb7', max_length=50, verbose_name='\u5faa\u73af\u4f53\u540d\u79f0')),
                ('xpath', models.CharField(help_text=b'\xe4\xbd\xbf\xe7\x94\xa8xpath\xe8\xa7\x84\xe5\x88\x99\xef\xbc\x9a\nnodename \xe9\x80\x89\xe6\x8b\xa9\xe6\x89\x80\xe6\x9c\x89\xe7\x9b\xae\xe5\x89\x8d\xe8\x8a\x82\xe7\x9a\x84\xe5\xad\x90\xe8\x8a\x82\n/ \xe4\xbb\x8e\xe6\xa0\xb9\xe8\x8a\x82\xe8\xbf\x9b\xe8\xa1\x8c\xe9\x80\x89\xe6\x8b\xa9\n// \xe9\x80\x89\xe6\x8b\xa9\xe6\x96\x87\xe6\xa1\xa3\xe4\xb8\xad\xe7\x9b\xb8\xe5\x90\xbb\xe5\x90\x88\xe7\x9a\x84\xe8\x8a\x82\xe8\x80\x8c\xe4\xb8\x8d\xe7\xae\xa1\xe5\x85\xb6\xe5\x9c\xa8\xe6\x96\x87\xe6\xa1\xa3\xe7\x9a\x84\xe4\xbd\x95\xe5\xa4\x84\n. \xe9\x80\x89\xe6\x8b\xa9\xe5\xbd\x93\xe5\x89\x8d\xe8\x8a\x82\n.. \xe5\xbd\x93\xe5\x89\x8d\xe8\x8a\x82\xe7\x9a\x84\xe7\x88\xb6\xe8\x8a\x82\n@ \xe9\x80\x89\xe6\x8b\xa9\xe5\xb1\x9e\xe6\x80\xa7', max_length=200, verbose_name='\u67e5\u8be2\u89c4\u5219')),
            ],
            options={
                'verbose_name': '\u5faa\u73af\u4f53\u5217\u8868',
                'verbose_name_plural': '\u5faa\u73af\u4f53\u5217\u8868\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='scrapyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='\u540d\u79f0')),
                ('priority', models.IntegerField(default=0, verbose_name='\u9879\u76ee\u4f18\u5148\u7ea7')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u722c\u866b\u5217\u8868',
                'verbose_name_plural': '\u722c\u866b\u5217\u8868\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='scrapySetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'\xe4\xb8\x8d\xe8\xa6\x81\xe8\xbe\x93\xe5\x85\xa5\xe4\xb8\xad\xe6\x96\x87\xe5\x92\x8c\xe7\x89\xb9\xe6\xae\x8a\xe7\xac\xa6\xe5\x8f\xb7', max_length=20, verbose_name='\u540d\u79f0')),
                ('num', models.IntegerField(default=1, verbose_name='\u5355\u4e2a\u4efb\u52a1\u94fe\u63a5\u6570')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modify_at', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('allow_domains', models.ManyToManyField(to='datadeal.AllowDomains', verbose_name='\u57df\u540d\u767d\u540d\u5355')),
                ('cycleobj', models.ManyToManyField(to='datadeal.CycleObj', verbose_name='\u5faa\u73af\u4f53')),
            ],
            options={
                'verbose_name': '\u722c\u866b\u914d\u7f6e',
                'verbose_name_plural': '\u722c\u866b\u914d\u7f6e\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='startUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u4e00\u7ea7\u722c\u53d6\u5730\u5740\u5217\u8868',
                'verbose_name_plural': '\u4e00\u7ea7\u722c\u53d6\u5730\u5740\u5217\u8868\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'\xe4\xb8\x8d\xe8\xa6\x81\xe8\xbe\x93\xe5\x85\xa5\xe4\xb8\xad\xe6\x96\x87\xe5\x92\x8c\xe7\x89\xb9\xe6\xae\x8a\xe7\xac\xa6\xe5\x8f\xb7,\xe5\xbb\xba\xe8\xae\xae\xe7\x94\xa8\xe5\xaf\xb9\xe5\xba\x94\xe7\x9a\x84\xe5\xbe\xaa\xe7\x8e\xaf\xe4\xbd\x93\xe5\x81\x9a\xe5\x89\x8d\xe7\xbc\x80\xe5\x8a\xa0\xe4\xbb\xa5\xe5\x8c\xba\xe5\x88\x86', max_length=50, verbose_name='\u53d8\u91cf\u540d\u79f0')),
                ('xpath', models.CharField(help_text=b'\xe4\xbd\xbf\xe7\x94\xa8xpath\xe8\xa7\x84\xe5\x88\x99\xef\xbc\x9a\nnodename \xe9\x80\x89\xe6\x8b\xa9\xe6\x89\x80\xe6\x9c\x89\xe7\x9b\xae\xe5\x89\x8d\xe8\x8a\x82\xe7\x9a\x84\xe5\xad\x90\xe8\x8a\x82\n/ \xe4\xbb\x8e\xe6\xa0\xb9\xe8\x8a\x82\xe8\xbf\x9b\xe8\xa1\x8c\xe9\x80\x89\xe6\x8b\xa9\n// \xe9\x80\x89\xe6\x8b\xa9\xe6\x96\x87\xe6\xa1\xa3\xe4\xb8\xad\xe7\x9b\xb8\xe5\x90\xbb\xe5\x90\x88\xe7\x9a\x84\xe8\x8a\x82\xe8\x80\x8c\xe4\xb8\x8d\xe7\xae\xa1\xe5\x85\xb6\xe5\x9c\xa8\xe6\x96\x87\xe6\xa1\xa3\xe7\x9a\x84\xe4\xbd\x95\xe5\xa4\x84\n. \xe9\x80\x89\xe6\x8b\xa9\xe5\xbd\x93\xe5\x89\x8d\xe8\x8a\x82\n.. \xe5\xbd\x93\xe5\x89\x8d\xe8\x8a\x82\xe7\x9a\x84\xe7\x88\xb6\xe8\x8a\x82\n@ \xe9\x80\x89\xe6\x8b\xa9\xe5\xb1\x9e\xe6\x80\xa7', max_length=200, verbose_name='\u67e5\u8be2\u89c4\u5219')),
                ('kind', models.IntegerField(choices=[(1, '\u4e00\u7ea7\u53d8\u91cf'), (2, '\u4e8c\u7ea7\u53d8\u91cf'), (3, '\u4e8c\u7ea7\u94fe\u63a5')], default=1, verbose_name='\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u53d8\u91cf\u5217\u8868',
                'verbose_name_plural': '\u53d8\u91cf\u5217\u8868\u7ba1\u7406',
            },
        ),
        migrations.AddField(
            model_name='scrapysetting',
            name='start_urls',
            field=models.ManyToManyField(to='datadeal.startUrls', verbose_name='\u4e00\u7ea7\u722c\u53d6\u5730\u5740\u5217\u8868'),
        ),
        migrations.AddField(
            model_name='cycleobj',
            name='variable',
            field=models.ManyToManyField(to='datadeal.Variable', verbose_name='\u53d8\u91cf'),
        ),
    ]
