# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadeal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='important',
            field=models.BooleanField(default=False, help_text=b'\xe8\x8b\xa5\xe8\xaf\xa5\xe5\x8f\x98\xe9\x87\x8f\xe6\x89\xbe\xe4\xb8\x8d\xe5\x88\xb0\xe6\x95\xb0\xe6\x8d\xae\xef\xbc\x8c\xe5\x88\x99\xe4\xb8\x8d\xe8\xbf\x9b\xe8\xa1\x8c\xe4\xb8\x8b\xe4\xb8\x80\xe6\xad\xa5', verbose_name='\u5173\u952e\u53d8\u91cf'),
        ),
    ]
