# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadeal', '0002_variable_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='all_text',
            field=models.BooleanField(default=False, help_text=b'\xe5\xb0\x86\xe6\x8f\x90\xe5\x8f\x96\xe8\xaf\xa5\xe6\xa0\x87\xe7\xad\xbe\xe4\xb8\x8b\xe6\x96\x87\xe6\x9c\xac\xe5\x8f\x8a\xe6\x89\x80\xe6\x9c\x89\xe5\xad\x90\xe6\xa0\x87\xe7\xad\xbe\xe6\x96\x87\xe6\x9c\xac\xef\xbc\x8c', verbose_name='\u5168\u6587\u672c\u63d0\u53d6'),
        ),
    ]
