# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadeal', '0003_variable_all_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapysetting',
            name='kind',
            field=models.IntegerField(choices=[(1, '\u5217\u8868\u53ca\u8be6\u60c5'), (2, '\u5217\u8868'), (3, '\u5355\u9875\u9762'), (4, '\u5176\u4ed6')], default=1, verbose_name='\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='scrapysetting',
            name='variable',
            field=models.ManyToManyField(blank=True, to='datadeal.Variable', verbose_name='\u975e\u5faa\u73af\u53d8\u91cf'),
        ),
        migrations.AlterField(
            model_name='scrapysetting',
            name='cycleobj',
            field=models.ManyToManyField(blank=True, to='datadeal.CycleObj', verbose_name='\u5faa\u73af\u4f53'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='all_text',
            field=models.BooleanField(default=False, help_text=b'\xe5\xb0\x86\xe6\x8f\x90\xe5\x8f\x96\xe8\xaf\xa5\xe6\xa0\x87\xe7\xad\xbe\xe4\xb8\x8b\xe6\x96\x87\xe6\x9c\xac\xe5\x8f\x8a\xe6\x89\x80\xe6\x9c\x89\xe5\xad\x90\xe6\xa0\x87\xe7\xad\xbe\xe6\x96\x87\xe6\x9c\xac,\xe5\xbc\x80\xe5\x90\xaf\xe5\x90\x8e\xe4\xb8\x8d\xe8\xa6\x81\xe5\x86\x99/text()', verbose_name='\u5b50\u6807\u7b7e\u6587\u672c\u63d0\u53d6'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='important',
            field=models.BooleanField(default=False, help_text=b'\xe8\x8b\xa5\xe8\xaf\xa5\xe5\x8f\x98\xe9\x87\x8f\xe6\x89\xbe\xe4\xb8\x8d\xe5\x88\xb0\xe6\x95\xb0\xe6\x8d\xae\xef\xbc\x8c\xe5\x88\x99\xe4\xb8\x8d\xe4\xbc\x9a\xe5\x8a\xa0\xe5\x85\xa5\xe5\x88\xb0\xe8\xbf\x94\xe5\x9b\x9e\xe6\x95\xb0\xe6\x8d\xae\xe4\xb8\xad', verbose_name='\u5173\u952e\u53d8\u91cf'),
        ),
    ]
