# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datadeal', '0004_auto_20170608_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='important',
        ),
    ]
