# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-05 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadeal', '0006_auto_20170703_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrapyname', models.CharField(max_length=50, verbose_name='\u9879\u76ee\u6765\u6e90')),
                ('uid', models.CharField(max_length=50, verbose_name='\u8bbe\u5907\u6765\u6e90')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('url', models.CharField(max_length=300, verbose_name='\u8bbf\u95ee\u5730\u5740')),
                ('content', models.CharField(max_length=300, verbose_name='\u9519\u8bef\u4fe1\u606f')),
            ],
            options={
                'verbose_name': '\u9519\u8bef\u4fe1\u606f',
                'verbose_name_plural': '\u9519\u8bef\u4fe1\u606f\u7ba1\u7406',
            },
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='scrapyname',
            field=models.CharField(max_length=50, verbose_name='\u9879\u76ee\u6765\u6e90'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='uid',
            field=models.CharField(max_length=50, verbose_name='\u8bbe\u5907\u6765\u6e90'),
        ),
    ]
