# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-20 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadeal', '0007_auto_20170705_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderdata',
            name='file',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u539f\u9875\u9762'),
        ),
        migrations.AddField(
            model_name='spiderdata',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='\u8bbf\u95ee\u5730\u5740'),
        ),
    ]
