# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-15 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadeal', '0008_auto_20170720_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAlarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrapyname', models.CharField(max_length=50, verbose_name='\u722c\u866b\u540d')),
                ('is_alarm', models.BooleanField(default=True, verbose_name='\u662f\u5426\u9884\u8b66')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='\u539f\u56e0\u5907\u6ce8')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u722c\u866b\u9884\u8b66',
                'verbose_name_plural': '\u722c\u866b\u9884\u8b66\u7ba1\u7406',
            },
        ),
        migrations.AddField(
            model_name='scrapylist',
            name='alarm_day',
            field=models.IntegerField(default=30, help_text=b'\xe8\xb6\x85\xe8\xbf\x87\xe6\x97\xb6\xe9\x97\xb4\xe6\x97\xa0\xe6\x95\xb0\xe6\x8d\xae\xe5\x88\x99\xe7\x94\x9f\xe6\x88\x90\xe9\xa2\x84\xe8\xad\xa6', verbose_name='\u9884\u8b66\u5929\u6570'),
        ),
        migrations.AddField(
            model_name='scrapylist',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u542f\u7528'),
        ),
        migrations.AlterField(
            model_name='errordata',
            name='scrapyname',
            field=models.CharField(max_length=50, verbose_name='\u722c\u866b\u540d'),
        ),
    ]
