# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-27 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u4f01\u4e1a\u540d\u79f0')),
                ('address', models.CharField(max_length=100, verbose_name='\u4f01\u4e1a\u5730\u5740')),
                ('creditcode', models.CharField(max_length=50, null=True, verbose_name='\u7edf\u4e00\u793e\u4f1a\u4fe1\u7528\u4ee3\u7801')),
                ('registration', models.CharField(max_length=50, verbose_name='\u6ce8\u518c\u53f7')),
                ('organization', models.CharField(max_length=50, null=True, verbose_name='\u7ec4\u7ec7\u673a\u6784\u4ee3\u7801')),
                ('kind', models.CharField(max_length=50, null=True, verbose_name='\u516c\u53f8\u7c7b\u578b')),
                ('status', models.CharField(max_length=50, null=True, verbose_name='\u7ecf\u8425\u72b6\u6001')),
                ('legalperson', models.CharField(max_length=50, verbose_name='\u6cd5\u5b9a\u4ee3\u8868\u4eba')),
                ('start_at', models.DateField(null=True, verbose_name='\u7ecf\u8425\u65e5\u671f')),
                ('capital', models.CharField(max_length=50, null=True, verbose_name='\u6ce8\u518c\u8d44\u672c')),
                ('deadline', models.CharField(max_length=50, null=True, verbose_name='\u8425\u4e1a\u671f\u9650')),
                ('give_at', models.DateField(null=True, verbose_name='\u53d1\u7167\u65e5\u671f')),
                ('webpage', models.CharField(max_length=50, null=True, verbose_name='\u7f51\u5740')),
                ('authority', models.CharField(max_length=50, null=True, verbose_name='\u767b\u8bb0\u673a\u5173')),
                ('scope', models.TextField(null=True, verbose_name='\u7ecf\u8425\u8303\u56f4')),
            ],
            options={
                'verbose_name': '\u516c\u53f8\u4fe1\u606f',
                'verbose_name_plural': '\u516c\u53f8\u4fe1\u606f\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u5b57')),
                ('kind', models.CharField(max_length=50, verbose_name='\u8eab\u4efd')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='\u516c\u53f8')),
            ],
            options={
                'verbose_name': '\u6210\u5458\u4fe1\u606f',
                'verbose_name_plural': '\u6210\u5458\u4fe1\u606f\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Shareholders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u80a1\u4e1c')),
                ('kind', models.CharField(max_length=50, verbose_name='\u7c7b\u578b')),
                ('subcribe_money', models.CharField(max_length=50, null=True, verbose_name='\u8ba4\u7f34\u51fa\u8d44\u91d1\u989d')),
                ('subcribe_date', models.DateField(null=True, verbose_name='\u8ba4\u7f34\u51fa\u8d44\u65f6\u95f4')),
                ('real_money', models.CharField(max_length=50, null=True, verbose_name='\u5b9e\u7f34\u51fa\u8d44\u91d1\u989d')),
                ('real_date', models.DateField(null=True, verbose_name='\u5b9e\u7f34\u51fa\u8d44\u65f6\u95f4')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='\u516c\u53f8')),
            ],
            options={
                'verbose_name': '\u80a1\u4e1c\u4fe1\u606f',
                'verbose_name_plural': '\u80a1\u4e1c\u4fe1\u606f\u7ba1\u7406',
            },
        ),
    ]
